# $NetBSD: Makefile.common,v 1.27 2026/08/18 18:26:07 adam Exp $
# used by x11/qt6-qtbase/Makefile.common

# When bumping the minor version (e.g., from 6.11 to 6.12), please
# always run a recursive revbump.
QTVERSION=	6.12.0

.include "../../mk/bsd.prefs.mk"

# EmberBSD: only the recipes prepared together in this toolkit export.
_EMBERBSD_QTVERSION_RECIPES= \
    audio/qt6-qtspeech \
    comms/qt6-qtconnectivity \
    devel/qt6-qt5compat \
    devel/qt6-qttools \
    devel/qt6-qtwayland \
    geography/qt6-qtpositioning \
    graphics/qt6-qtcharts \
    graphics/qt6-qtimageformats \
    graphics/qt6-qtquick3d \
    graphics/qt6-qtquicktimeline \
    graphics/qt6-qtshadertools \
    graphics/qt6-qtsvg \
    inputmethod/qt6-qtvirtualkeyboard \
    lang/qt6-qtdeclarative \
    lang/qt6-qtlanguageserver \
    misc/qt6-qtsensors \
    multimedia/qt6-qtmultimedia \
    net/qt6-qtwebsockets \
    security/qt6-qtnetworkauth \
    x11/qt6-qtbase \
    x11/qt6-qtserialport \
    x11/qt6-qttranslations
.if empty(_EMBERBSD_QTVERSION_RECIPES:M${PKGPATH})
PKG_FAIL_REASON+= "Qt 6 recipe ${PKGPATH} is not prepared in the Plasma toolkit"
.endif
.if ${QTVERSION} != "6.12.0"
PKG_FAIL_REASON+= "The common toolkit requires QTVERSION=6.12.0"
.endif
GCC_REQD+= 16.2




MASTER_SITES=	https://download.qt.io/archive/qt/${QTVERSION:R}/${QTVERSION}/submodules/

EXTRACT_SUFX=	.tar.xz
EXTRACT_USING=	bsdtar

MAINTAINER?=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://www.qt.io/

# The qt6 packages install with prefix being a qt6 subdirectory, so
# that it can be installed in parallel with qt5, rather than being an
# alternative.  Various things may be necessary to use it from outside
# of pkgsrc:
#   1) Use the "configure" argument "--with-qt-dir=${PREFIX}/qt6"
#   2) Use the "cmake" argument "-DCMAKE_SYSTEM_PREFIX_PATH:PATH=${PREFIX}/qt6"
#   3) you may also have to put ${PREFIX}/qt6/bin in your PATH
QTPREFIX=	${PREFIX}/qt6
