# SPDX-License-Identifier: MIT
set(CMAKE_SYSTEM_NAME NetBSD)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
foreach(required EMBER_CROSS_PREFIX EMBER_SYSROOT)
  if(NOT DEFINED ENV{${required}} OR "$ENV{${required}}" STREQUAL "")
    message(FATAL_ERROR "Set ${required} in the environment")
  endif()
endforeach()
set(CMAKE_C_COMPILER "$ENV{EMBER_CROSS_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "$ENV{EMBER_CROSS_PREFIX}g++")
set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
set(CMAKE_SYSROOT "$ENV{EMBER_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(_gcc "${CMAKE_SYSROOT}/usr/pkg/gcc16")
set(CMAKE_C_FLAGS_INIT "-B${_gcc}/lib/gcc/aarch64--netbsd/16.2.0/")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} -isystem ${_gcc}/include/c++ -isystem ${_gcc}/include/c++/aarch64--netbsd -isystem ${_gcc}/include/c++/backward")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-L${_gcc}/lib -Wl,-rpath,/usr/pkg/gcc16/lib")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT}")
