# Production closure of LiteRT-LM v0.18.0 engine_advanced_impl_cpu_only.
# NPU, debugger and HuggingFace tokenizer are disabled using upstream guards.
set(EMBER_LM_SOURCES
  runtime/components/constrained_decoding/composite_constraint.cc
  runtime/components/constrained_decoding/constrained_decoder.cc
  runtime/components/constrained_decoding/constraint.cc
  runtime/components/constrained_decoding/logit_mask.cc
  runtime/components/constrained_decoding/no_repeat_ngram_constraint.cc
  runtime/components/constrained_decoding/repetition_penalty_constraint.cc
  runtime/components/constrained_decoding/suppress_tokens_constraint.cc
  runtime/components/constrained_decoding/thinking_budget_constraint.cc
  runtime/components/embedding_lookup/embedding_lookup_end_of_multi_modal.cc
  runtime/components/embedding_lookup/embedding_lookup_manager.cc
  runtime/components/embedding_lookup/embedding_lookup_multi_modal.cc
  runtime/components/embedding_lookup/embedding_lookup_text.cc
  runtime/components/lora.cc
  runtime/components/lora_manager.cc
  runtime/components/model_resources.cc
  runtime/components/model_resources_litert_lm.cc
  runtime/components/model_resources_task.cc
  runtime/components/sampler_factory.cc
  runtime/components/sampling_cpu_util.cc
  runtime/components/scoring_cpu_util.cc
  runtime/components/stop_token_detector.cc
  runtime/components/top_p_cpu_sampler.cc
  runtime/core/audio_session_advanced.cc
  runtime/core/cached_session.cc
  runtime/core/engine_advanced_impl.cc
  runtime/core/prefix_cache.cc
  runtime/core/session_advanced.cc
  runtime/core/session_utils.cc
  runtime/core/tasks.cc
  runtime/engine/cpu_affinity_utils.cc
  runtime/engine/embedding_engine_settings.cc
  runtime/engine/engine_settings.cc
  runtime/engine/io_types.cc
  runtime/executor/audio/audio_executor_settings.cc
  runtime/executor/audio/audio_executor_utils.cc
  runtime/executor/audio_litert_compiled_model_executor.cc
  runtime/executor/common_utils.cc
  runtime/executor/embedding/embedding_executor_settings.cc
  runtime/executor/executor_settings_base.cc
  runtime/executor/executor_stats.cc
  runtime/executor/litert/state.cc
  runtime/executor/litert_compiled_model_executor_utils.cc
  runtime/executor/llm_executor_io_types.cc
  runtime/executor/llm_executor_processed_tokens.cc
  runtime/executor/llm_executor_settings.cc
  runtime/executor/llm_executor_settings_utils.cc
  runtime/executor/llm_litert_compiled_model_cache_utils.cc
  runtime/executor/llm_litert_compiled_model_executor.cc
  runtime/executor/llm_litert_compiled_model_executor_factory.cc
  runtime/executor/llm_litert_mtp_drafter.cc
  runtime/executor/magic_number_configs_helper.cc
  runtime/executor/model_signature_utils.cc
  runtime/executor/vision/vision_executor_settings.cc
  runtime/executor/vision/vision_executor_utils.cc
  runtime/executor/vision_litert_compiled_model_executor.cc
  runtime/framework/resource_management/context_handler/context_handler.cc
  runtime/framework/resource_management/resource_manager.cc
  runtime/framework/resource_management/serial_execution_manager.cc
  runtime/framework/resource_management/threaded_execution_manager.cc
  runtime/framework/resource_management/utils/resource_manager_utils.cc
  runtime/framework/threadpool.cc
  runtime/framework/worker_thread.cc
  runtime/framework/worker_thread_pthread.cc
  runtime/util/data_stream.cc
  runtime/util/executor_data_util.cc
  runtime/util/file_format_util.cc
  runtime/util/file_util.cc
  runtime/util/litert_lm_loader.cc
  runtime/util/litert_util.cc
  runtime/util/log_tensor_buffer.cc
  runtime/util/logging.cc
  runtime/util/logging_tensor_buffer.cc
  runtime/util/lora_data.cc
  runtime/util/lora_util.cc
  runtime/util/metadata_util.cc
  runtime/util/model_asset_bundle_resources.cc
  runtime/util/model_type_utils.cc
  runtime/util/safetensors_util.cc
  runtime/util/tensor_buffer_util.cc
  runtime/util/zip_readonly_mem_file.cc
  runtime/util/zip_utils.cc
  schema/core/litertlm_read.cc
  schema/core/litertlm_utils.cc
  support/tokenizer/buffered_streaming_detokenizer.cc
  support/tokenizer/sentencepiece_tokenizer.cc
  support/util/io_types.cc
  support/util/memory_mapped_file_posix.cc
)
