# Original MediaPipe metadata fields 6, 5 and 8, expressed as LlmMetadata.
start_token { token_str: "<s>" }
stop_tokens { token_str: "</s>" }
prompt_templates {
  user {
    prefix: "<|user|>\\n"
    suffix: "</s>\\n<|assistant|>\\n"
  }
}
